<?php

namespace frontend\api\controllers;

use frontend\models\ChatMessage;
use Yii;
use yii\rest\ActiveController;

class MessagesController extends ActiveController
{
    public $modelClass = ChatMessage::class;

    public function actions()
    {
        $actions = parent::actions();
        unset($actions['view'], $actions['update'], $actions['delete']);

        return $actions;
    }

    public function beforeAction($action)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $data = json_decode(Yii::$app->getRequest()->getRawBody());
        $_POST['message'] = $data->message ?? '';
        $_POST['task_id'] = $data->task_id ?? '';

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}