<?php

namespace frontend\controllers;

use frontend\components\LandingComponent;
use frontend\models\forms\UserLoginForm;
use Yii;

class LandingController extends UnsecuredController
{
    public $layout = 'landing';
    public UserLoginForm $model;

    public function actionIndex()
    {
        if (Yii::$app->request->getIsPost()) {
            return LandingComponent::login($this->model);
        }

        return $this->render('index', LandingComponent::getDataForLandingPage());
    }

    public function beforeAction($action)
    {
        $this->model = new UserLoginForm();
        $this->enableCsrfValidation = false;

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
