<?php

namespace frontend\controllers;

use frontend\components\helpers\TimeOperations;
use frontend\components\LandingComponent;
use frontend\components\traits\TaskFiltersTrait;
use frontend\models\forms\UserLoginForm;
use Illuminate\Http\Response;
use Yii;
use yii\web\Controller;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

class LandingController extends Controller
{
    public $layout = 'landing';
    public UserLoginForm $model;

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function actionIndex()
    {
        $request = \Yii::$app->request;
        $this->model = new UserLoginForm();

        if ($request->getIsPost()) {
            $this->model->load($request->post());
            if ($request->isAjax) {
                if (ActiveForm::validate($this->model) == []) {
                    $user = $this->model->getUser();
                    return Yii::$app->user->login($user);
                }
                return json_encode(ActiveForm::validate($this->model));
            }
        }

        $data = LandingComponent::getDataForLandingPage($this->model);
        return $this->render('index', $data);
    }
}