<?php

namespace frontend\controllers;

use frontend\controllers\parentControllers\SecuredController;
use frontend\models\Category;
use frontend\models\City;
use frontend\models\forms\UserProfileSettingsForm;
use Yii;
use frontend\components\user\AuthUserComponent;

class ProfileController extends SecuredController
{
    public $enableCsrfValidation = false;
    private UserProfileSettingsForm $model;

    public function actionIndex()
    {
        Yii::$app->user->identity->selectedCategories = AuthUserComponent::getAuthUserCategories();
        return $this->render(
            'index',
            [
                'model' => $this->model,
                'user' => Yii::$app->user->identity,
                'cities' => City::getCities(),
                'categories' => Category::getCategoriesListArray(),
            ]
        );
    }

    public function actionUpdate()
    {
        //$result = Yii::$app->authUserComponent->updateAuthUserProfile($this->model);
        $result = $this->model->update();

        if (Yii::$app->request->isAjax) {
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            return $result;
        }
        return $this->redirectBack();
    }

    public function actionUpdatePortfolio()
    {
        try {
            if (Yii::$app->request->isAjax) {
                \Yii::$app->authUserComponent->updateAuthUserPortfolio();
            }
            return $this->redirectBack();
        } catch (\Exception $e) {
            return $e->getMessage();
        }
    }

    public function beforeAction($action)
    {
        Yii::$app->request->enableCsrfValidation = false;
        //$this->enableCsrfValidation = false;
        $this->model = new UserProfileSettingsForm();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}