<?php

namespace frontend\controllers;

use frontend\components\traits\QueriesTrait;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;

class SecuredController extends Controller
{
    use QueriesTrait;

    public $userName;
    public $userPhoto;

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ]
        ];
    }

    public function beforeAction($action)
    {
        $userId = Yii::$app->user->getId();

        $this->userName = self::findUserName($userId);
        $this->userPhoto = self::findUsersPhoto($userId);
        Yii::$app->user->loginUrl = ['/ '];
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}